"""Update models - add user_usuario and fix trabajadores_apoyo

Revision ID: 334c1111c2a4
Revises: 9fdc555a42ed
Create Date: 2025-09-16 12:26:46.087454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334c1111c2a4'
down_revision = '9fdc555a42ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Primero actualizamos trabajadores_apoyo
    with op.batch_alter_table('trabajadores_apoyo', schema=None) as batch_op:
        batch_op.alter_column('apellidos',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('cargo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('telefono')
        batch_op.drop_column('correo_electronico')
        batch_op.drop_column('fecha_nacimiento')

    # Luego actualizamos usuarios de forma segura
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        # Primero agregar la columna como nullable
        batch_op.add_column(sa.Column('user_usuario', sa.String(length=150), nullable=True))
    
    # Actualizar todos los registros existentes con el RUT como valor por defecto
    op.execute("UPDATE usuarios SET user_usuario = rut_usuario WHERE user_usuario IS NULL")
    
    # Ahora cambiar la columna a NOT NULL
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('user_usuario',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('user_usuario')

    with op.batch_alter_table('trabajadores_apoyo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('correo_electronico', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(length=9), autoincrement=False, nullable=False))
        batch_op.alter_column('cargo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('apellidos',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
