"""Initial migration with all models

Revision ID: 9fdc555a42ed
Revises: 
Create Date: 2025-09-12 09:51:48.399196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fdc555a42ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_actividades_fecha_inicio'))
        batch_op.drop_index(batch_op.f('idx_actividades_persona_a_cargo'))

    with op.batch_alter_table('centros_comunitarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_centros_comunitarios_nombre'))
        batch_op.drop_index(batch_op.f('idx_centros_comunitarios_sector'))

    with op.batch_alter_table('gestiona', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_gestiona_fecha'))
        batch_op.drop_index(batch_op.f('idx_gestiona_tipo'))

    with op.batch_alter_table('mantenciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_mantenciones_centro'))
        batch_op.drop_index(batch_op.f('idx_mantenciones_fecha'))

    with op.batch_alter_table('participa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_participa_fecha'))
        batch_op.drop_index(batch_op.f('idx_participa_tipo'))

    with op.batch_alter_table('personas_a_cargo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_personas_a_cargo_correo'))
        batch_op.drop_index(batch_op.f('idx_personas_a_cargo_telefono'))

    with op.batch_alter_table('personas_mayores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_personas_mayores_fecha_nacimiento'))
        batch_op.drop_index(batch_op.f('idx_personas_mayores_genero'))
        batch_op.drop_index(batch_op.f('idx_personas_mayores_sector'))

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_servicios_estado'))
        batch_op.drop_index(batch_op.f('idx_servicios_fecha'))
        batch_op.drop_index(batch_op.f('idx_servicios_persona_a_cargo'))

    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_talleres_fecha_inicio'))
        batch_op.drop_index(batch_op.f('idx_talleres_persona_a_cargo'))

    with op.batch_alter_table('trabajadores_apoyo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_trabajadores_apoyo_cargo'))
        batch_op.drop_index(batch_op.f('idx_trabajadores_apoyo_centro'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores_apoyo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_trabajadores_apoyo_centro'), ['id_centro'], unique=False)
        batch_op.create_index(batch_op.f('idx_trabajadores_apoyo_cargo'), ['cargo'], unique=False)

    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_talleres_persona_a_cargo'), ['persona_a_cargo'], unique=False)
        batch_op.create_index(batch_op.f('idx_talleres_fecha_inicio'), ['fecha_inicio'], unique=False)

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_servicios_persona_a_cargo'), ['persona_a_cargo'], unique=False)
        batch_op.create_index(batch_op.f('idx_servicios_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('idx_servicios_estado'), ['estado'], unique=False)

    with op.batch_alter_table('personas_mayores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_personas_mayores_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('idx_personas_mayores_genero'), ['genero'], unique=False)
        batch_op.create_index(batch_op.f('idx_personas_mayores_fecha_nacimiento'), ['fecha_nacimiento'], unique=False)

    with op.batch_alter_table('personas_a_cargo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_personas_a_cargo_telefono'), ['telefono'], unique=False)
        batch_op.create_index(batch_op.f('idx_personas_a_cargo_correo'), ['correo_electronico'], unique=False)

    with op.batch_alter_table('participa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_participa_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('idx_participa_fecha'), ['fecha_participacion'], unique=False)

    with op.batch_alter_table('mantenciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_mantenciones_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('idx_mantenciones_centro'), ['id_centro'], unique=False)

    with op.batch_alter_table('gestiona', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_gestiona_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('idx_gestiona_fecha'), ['fecha_asignacion'], unique=False)

    with op.batch_alter_table('centros_comunitarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_centros_comunitarios_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('idx_centros_comunitarios_nombre'), ['nombre'], unique=False)

    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_actividades_persona_a_cargo'), ['persona_a_cargo'], unique=False)
        batch_op.create_index(batch_op.f('idx_actividades_fecha_inicio'), ['fecha_inicio'], unique=False)

    # ### end Alembic commands ###
